#!/bin/sh

# Colors
GREEN="\033[1;32m"
GREEN_BG="\033[1;42m"
RED="\033[0;31m"
RED_BG="\033[1;41m"
YELLOW="\033[1;33m"
YELLOW_BG="\033[1;43m"
RESET="\033[0m"

# Start server
if [ "$1" = "start" ] || [ "$1" = "run" ]; then
    echo "${GREEN}[INFO] Starting server... ${GREEN_BG}"
    exec npm run qwees:start
else
    echo "${RED}⊗ WARNING ${RESET}: No command provided. Please, use: ${YELLOW_BG} qwees start ${RESET} or ${YELLOW_BG} qwees run ${RESET}"
    exit 1
fi
